#!/usr/bin/env python3
"""nb2pdf_agent.py — Jupyter Notebook to Professional PDF"""
import argparse, base64, re, os
from io import BytesIO
from datetime import datetime
import nbformat
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, PageBreak, HRFlowable, Image)
from reportlab.pdfgen import canvas
from PIL import Image as PILImage

C_DARK =colors.HexColor("#1a1a2e"); C_ACCENT=colors.HexColor("#4361ee")
C_ACCENT2=colors.HexColor("#3a0ca3"); C_CODE_BG=colors.HexColor("#f8f9fa")
C_CODE_BD=colors.HexColor("#dee2e6"); C_OUT_BG=colors.HexColor("#f0f4ff")
C_OUT_BD=colors.HexColor("#4361ee"); C_ERR_BG=colors.HexColor("#fff5f5")
C_ERR_BD=colors.HexColor("#e53e3e"); C_H1=colors.HexColor("#1a1a2e")
C_H2=colors.HexColor("#4361ee"); C_H3=colors.HexColor("#3a0ca3")
C_TEXT=colors.HexColor("#2d3748"); C_MUTED=colors.HexColor("#718096")
C_WHITE=colors.white; C_LGRAY=colors.HexColor("#e2e8f0")
PAGE_W,PAGE_H=A4; MARGIN=2.2*cm; IW=PAGE_W-2*MARGIN; MAX_LINES=50

class ReportCanvas(canvas.Canvas):
    def __init__(self,*a,doc_title="Notebook Report",**kw):
        super().__init__(*a,**kw)
        self._saved=[]; self.doc_title=doc_title
    def showPage(self):
        self._saved.append(dict(self.__dict__)); self._startPage()
    def save(self):
        t=len(self._saved)
        for s in self._saved:
            self.__dict__.update(s); self._paint(t); canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)
    def _paint(self,total):
        n=self.__dict__.get("_pageNumber",1)
        self.setFillColor(C_DARK); self.rect(0,PAGE_H-1.2*cm,PAGE_W,1.2*cm,fill=1,stroke=0)
        self.setFillColor(C_WHITE); self.setFont("Helvetica-Bold",9)
        self.drawString(MARGIN,PAGE_H-0.76*cm,self.doc_title)
        self.setFont("Helvetica",8)
        self.drawRightString(PAGE_W-MARGIN,PAGE_H-0.76*cm,datetime.now().strftime("%B %d, %Y"))
        self.setStrokeColor(C_ACCENT); self.setLineWidth(2)
        self.line(0,PAGE_H-1.25*cm,PAGE_W,PAGE_H-1.25*cm)
        self.setStrokeColor(C_LGRAY); self.setLineWidth(0.5)
        self.line(MARGIN,1.4*cm,PAGE_W-MARGIN,1.4*cm)
        self.setFillColor(C_MUTED); self.setFont("Helvetica",7.5)
        self.drawString(MARGIN,0.8*cm,"Generated by nb2pdf_agent")
        self.setFillColor(C_ACCENT); self.setFont("Helvetica-Bold",8)
        self.drawRightString(PAGE_W-MARGIN,0.8*cm,f"Page {n} of {total}")

def mk_styles():
    S=lambda n,**k:ParagraphStyle(n,**k)
    return {
        "H1":S("H1",fontName="Helvetica-Bold",fontSize=20,textColor=C_H1,spaceBefore=18,spaceAfter=8,leading=26),
        "H2":S("H2",fontName="Helvetica-Bold",fontSize=15,textColor=C_H2,spaceBefore=14,spaceAfter=6,leading=20),
        "H3":S("H3",fontName="Helvetica-Bold",fontSize=12,textColor=C_H3,spaceBefore=10,spaceAfter=4,leading=16),
        "H4":S("H4",fontName="Helvetica-BoldOblique",fontSize=10,textColor=C_ACCENT,spaceBefore=8,spaceAfter=3,leading=14),
        "body":S("body",fontName="Helvetica",fontSize=10,textColor=C_TEXT,spaceAfter=5,leading=16,alignment=TA_JUSTIFY),
        "bullet":S("bullet",fontName="Helvetica",fontSize=10,textColor=C_TEXT,spaceAfter=3,leading=14,leftIndent=14),
        "code":S("code",fontName="Courier",fontSize=8.5,textColor=colors.HexColor("#24292e"),leading=13,spaceAfter=0),
        "clbl":S("clbl",fontName="Helvetica-Bold",fontSize=7.5,textColor=C_MUTED,leading=10),
        "out":S("out",fontName="Courier",fontSize=8,textColor=C_TEXT,leading=12,spaceAfter=0),
        "err":S("err",fontName="Courier",fontSize=8,textColor=colors.HexColor("#c53030"),leading=12,spaceAfter=0),
        "toc1":S("toc1",fontName="Helvetica-Bold",fontSize=10,textColor=C_H1,spaceAfter=4,leading=14),
        "toc2":S("toc2",fontName="Helvetica",fontSize=9,textColor=C_H2,spaceAfter=2,leading=12,leftIndent=12),
        "toc3":S("toc3",fontName="Helvetica",fontSize=8.5,textColor=C_TEXT,spaceAfter=1,leading=11,leftIndent=24),
        "ct":S("ct",fontName="Helvetica-Bold",fontSize=30,textColor=C_WHITE,leading=38,alignment=TA_CENTER),
        "cs":S("cs",fontName="Helvetica",fontSize=12,textColor=colors.HexColor("#a0aec0"),leading=18,alignment=TA_CENTER),
        "cm":S("cm",fontName="Helvetica",fontSize=10,textColor=C_WHITE,leading=14,alignment=TA_CENTER),
    }

def xe(t): return t.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")

def mdi(t):
    t=xe(t)
    t=re.sub(r'\*\*\*(.+?)\*\*\*',r'<b><i>\1</i></b>',t)
    t=re.sub(r'\*\*(.+?)\*\*',r'<b>\1</b>',t); t=re.sub(r'__(.+?)__',r'<b>\1</b>',t)
    t=re.sub(r'\*(.+?)\*',r'<i>\1</i>',t); t=re.sub(r'_(.+?)_',r'<i>\1</i>',t)
    t=re.sub(r'`(.+?)`',r'<font name="Courier" size="9"><b>\1</b></font>',t)
    t=re.sub(r'\[(.+?)\]\(.+?\)',r'<u>\1</u>',t); return t

def block(lines, st, story, label=None, bg=None, bdc=None, tsk="code"):
    bg=bg or C_CODE_BG; bdc=bdc or C_CODE_BD
    fs="8.5" if tsk=="code" else "8"
    data=[]
    if label:
        data.append([Paragraph(xe(label), st["clbl"])])
    for ln in lines:
        esc=xe(ln) if ln.strip() else "\u00a0"
        data.append([Paragraph(f'<font name="Courier" size="{fs}">{esc}</font>', st[tsk])])
    if not data: return
    tbl=Table(data, colWidths=[IW], splitByRow=1)
    cmds=[
        ("BACKGROUND",   (0,0),(-1,-1),bg),
        ("LEFTPADDING",  (0,0),(-1,-1),12),
        ("RIGHTPADDING", (0,0),(-1,-1),8),
        ("TOPPADDING",   (0,0),(-1,-1),1),
        ("BOTTOMPADDING",(0,0),(-1,-1),1),
        ("BOX",          (0,0),(-1,-1),0.8,bdc),
        ("LINEBEFORE",   (0,0),(0,-1), 4, C_ACCENT if tsk=="code" else bdc),
    ]
    if label: cmds+=[ ("TOPPADDING",(0,0),(0,0),5), ("BOTTOMPADDING",(0,0),(0,0),3) ]
    tbl.setStyle(TableStyle(cmds))
    story.append(tbl); story.append(Spacer(1,4))

def render_code(source, st, story, n=None):
    if not source.strip(): return
    block(source.splitlines(), st, story, label=f"In [{n}]:" if n else None)

def render_outputs(outputs, n, st, story):
    for o in outputs:
        ot=o.get("output_type",""); is_err=ot=="error"
        lines=[]
        if ot=="stream":
            raw=o.get("text","")
            if isinstance(raw,list): raw="".join(raw)
            lines=raw.splitlines()
        elif ot in ("display_data","execute_result"):
            raw=o.get("data",{}).get("text/plain","")
            if isinstance(raw,list): raw="".join(raw)
            lines=raw.splitlines()
        elif is_err:
            lines=[f"{o.get('ename','Error')}: {o.get('evalue','')}"] + \
                  [re.sub(r'\x1b\[[0-9;]*m','',t) for t in o.get("traceback",[])]
        img=None
        if ot in ("display_data","execute_result"):
            d=o.get("data",{}); img=d.get("image/png") or d.get("image/jpeg")
        if not lines and not img: continue
        lbl=f"Out [{n}]:" if ot=="execute_result" else (f"Error [{n}]:" if is_err else f"[{ot}]:")
        if len(lines)>MAX_LINES: lines=lines[:MAX_LINES]+[f"... {len(lines)-MAX_LINES} more lines ..."]
        if lines:
            block(lines, st, story, label=lbl,
                  bg=C_ERR_BG if is_err else C_OUT_BG,
                  bdc=C_ERR_BD if is_err else C_OUT_BD,
                  tsk="err" if is_err else "out")
        if img:
            try:
                raw=base64.b64decode(img) if isinstance(img,str) else img
                pil=PILImage.open(BytesIO(raw)); pw,ph=pil.size
                dw=min(IW-20,pw); dh=dw*ph/pw
                buf=BytesIO(); pil.save(buf,format="PNG"); buf.seek(0)
                story.append(Image(buf,width=dw,height=dh)); story.append(Spacer(1,4))
            except: story.append(Paragraph("<i>[image error]</i>",st["body"]))

def md_table(rows,st,story):
    if not rows: return
    nc=max(len(r) for r in rows); cw=IW/nc
    data=[[Paragraph(f'<font name="{"Helvetica-Bold" if ri==0 else "Helvetica"}" size="9">{mdi(c)}</font>',st["body"])
           for c in (r+[""]*(nc-len(r)))] for ri,r in enumerate(rows)]
    t=Table(data,colWidths=[cw]*nc,splitByRow=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),C_ACCENT),("TEXTCOLOR",(0,0),(-1,0),C_WHITE),
        ("GRID",(0,0),(-1,-1),0.5,C_LGRAY),("ROWBACKGROUNDS",(0,1),(-1,-1),[C_WHITE,C_CODE_BG]),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),5),
        ("BOTTOMPADDING",(0,0),(-1,-1),5),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),
    ]))
    story.append(Spacer(1,4)); story.append(t); story.append(Spacer(1,6))

def parse_md(src,st,story,toc):
    lines=src.split('\n'); in_code=False; code_buf=[]; in_tbl=False; tbl_rows=[]; pbuf=[]
    def fp():
        if pbuf:
            t=" ".join(pbuf).strip()
            if t: story.append(Paragraph(mdi(t),st["body"]))
            pbuf.clear()
    def ft():
        nonlocal in_tbl,tbl_rows
        if tbl_rows: md_table(tbl_rows,st,story); tbl_rows.clear()
        in_tbl=False
    i=0
    while i<len(lines):
        ln=lines[i]
        if ln.strip().startswith("```"):
            fp()
            if not in_code: in_code=True; code_buf=[]
            else:
                in_code=False; block(code_buf,st,story); code_buf=[]
            i+=1; continue
        if in_code: code_buf.append(ln); i+=1; continue
        m=re.match(r'^(#{1,4})\s+(.*)',ln)
        if m:
            fp(); ft(); lv=len(m.group(1)); txt=m.group(2).strip()
            anc=f"h{len(toc)}"; toc.append((lv,txt,anc))
            if lv==1: story.append(Spacer(1,4)); story.append(HRFlowable(width="100%",thickness=2,color=C_ACCENT,spaceAfter=4))
            story.append(Paragraph(f'<a name="{anc}"/>{mdi(txt)}',st[f"H{min(lv,4)}"])); i+=1; continue
        if re.match(r'^[-*_]{3,}\s*$',ln):
            fp(); story.append(HRFlowable(width="100%",thickness=0.5,color=C_LGRAY,spaceBefore=4,spaceAfter=4)); i+=1; continue
        m=re.match(r'^(\s*)[-*+]\s+(.*)',ln)
        if m:
            fp(); ind=len(m.group(1))
            story.append(Paragraph(f'{"•" if ind==0 else "◦"}  {mdi(m.group(2))}',
                ParagraphStyle("_bl",parent=st["bullet"],leftIndent=14+ind*8))); i+=1; continue
        m=re.match(r'^(\s*)\d+\.\s+(.*)',ln)
        if m:
            fp(); ind=len(m.group(1))
            num=sum(1 for l in lines[:i] if re.match(r'^\s*\d+\.\s',l))+1
            story.append(Paragraph(f'{num}.  {mdi(m.group(2))}',
                ParagraphStyle("_ol",parent=st["bullet"],leftIndent=14+ind*8))); i+=1; continue
        if '|' in ln and ln.strip().startswith('|'):
            fp(); in_tbl=True
            if re.match(r'^\|[\s\-:|]+\|',ln): i+=1; continue
            tbl_rows.append([c.strip() for c in ln.strip().strip('|').split('|')]); i+=1; continue
        elif in_tbl: ft()
        if ln.strip()=="": fp(); story.append(Spacer(1,4)); i+=1; continue
        m=re.match(r'^>\s?(.*)',ln)
        if m:
            fp(); story.append(Paragraph(mdi(m.group(1)),
                ParagraphStyle("_bq",parent=st["body"],leftIndent=14,textColor=C_MUTED,
                               borderPadding=(3,6,3,6),borderColor=C_ACCENT2,borderWidth=2))); i+=1; continue
        pbuf.append(ln); i+=1
    fp(); ft()

def cover(path,nb,story,st):
    title=nb.get("metadata",{}).get("title") or os.path.splitext(os.path.basename(path))[0]
    kernel=nb.get("metadata",{}).get("kernelspec",{}).get("display_name","Python 3")
    ver=nb.get("metadata",{}).get("language_info",{}).get("version","")
    cells=nb.get("cells",[]); date=datetime.now().strftime("%B %d, %Y")
    inn=Table([
        [Paragraph("NOTEBOOK REPORT",ParagraphStyle("_tag",fontName="Helvetica",fontSize=10,
            textColor=colors.HexColor("#a0aec0"),alignment=TA_CENTER))],
        [Spacer(1,10)],[Paragraph(xe(title),st["ct"])],[Spacer(1,14)],
        [HRFlowable(width="50%",thickness=2,color=C_ACCENT)],[Spacer(1,14)],
        [Paragraph(f"Kernel: {kernel}"+(f"  ·  Python {ver}" if ver else ""),st["cs"])],
        [Spacer(1,6)],[Paragraph(f"Cells: {len(cells)}  ·  {date}",st["cm"])],
    ],colWidths=[PAGE_W-2*MARGIN],style=TableStyle([
        ("ALIGN",(0,0),(-1,-1),"CENTER"),("TOPPADDING",(0,0),(-1,-1),3),("BOTTOMPADDING",(0,0),(-1,-1),3)]))
    cvr=Table([[inn]],colWidths=[PAGE_W],rowHeights=[PAGE_H*0.5],style=TableStyle([
        ("BACKGROUND",(0,0),(-1,-1),C_DARK),("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("LEFTPADDING",(0,0),(-1,-1),MARGIN),("RIGHTPADDING",(0,0),(-1,-1),MARGIN)]))
    story.append(cvr); story.append(Spacer(1,1.2*cm))
    cc=sum(1 for c in cells if c.get("cell_type")=="code")
    mc=sum(1 for c in cells if c.get("cell_type")=="markdown")
    cw=IW/4; cols=[]
    for ico,lbl,val in [("📓","Total",str(len(cells))),("💻","Code",str(cc)),
                         ("📝","Markdown",str(mc)),("🐍","Kernel",kernel)]:
        cols.append(Table([
            [Paragraph(ico,ParagraphStyle("_i",fontSize=18,alignment=TA_CENTER))],
            [Paragraph(f"<b>{val}</b>",ParagraphStyle("_v",fontName="Helvetica-Bold",
                fontSize=13,textColor=C_ACCENT,alignment=TA_CENTER))],
            [Paragraph(lbl,ParagraphStyle("_l",fontName="Helvetica",fontSize=8,
                textColor=C_MUTED,alignment=TA_CENTER))],
        ],colWidths=[cw-6],style=TableStyle([("BOX",(0,0),(-1,-1),0.5,C_LGRAY),
            ("BACKGROUND",(0,0),(-1,-1),C_CODE_BG),("TOPPADDING",(0,0),(-1,-1),8),
            ("BOTTOMPADDING",(0,0),(-1,-1),8)])))
    story.append(Table([cols],colWidths=[cw]*4,style=TableStyle([
        ("LEFTPADDING",(0,0),(-1,-1),3),("RIGHTPADDING",(0,0),(-1,-1),3)])))
    story.append(PageBreak())

def toc_page(entries,st,story):
    story.append(Paragraph("Table of Contents",st["H1"]))
    story.append(HRFlowable(width="100%",thickness=2,color=C_ACCENT,spaceAfter=10))
    for lv,txt,anc in entries:
        story.append(Paragraph(
            f'{"▶" if lv==1 else ("  ›" if lv==2 else "    –")}  '
            f'<a href="#{anc}" color="#4361ee">{xe(txt)}</a>',
            ParagraphStyle(f"_t{lv}",parent=st[f"toc{min(lv,3)}"],leftIndent=(lv-1)*14)))
    story.append(PageBreak())

def convert_notebook(ipynb_path, output_path=None):
    if not os.path.exists(ipynb_path): raise FileNotFoundError(ipynb_path)
    with open(ipynb_path,encoding="utf-8") as f: nb=nbformat.read(f,as_version=4)
    if not output_path: output_path=os.path.splitext(ipynb_path)[0]+"_report.pdf"
    title=nb.get("metadata",{}).get("title") or os.path.splitext(os.path.basename(ipynb_path))[0]
    st=mk_styles(); story=[]; toc=[]
    cover(ipynb_path,nb,story,st)
    ti=len(story); story.append(None)
    cn=1
    for cell in nb.get("cells",[]):
        ct=cell.get("cell_type",""); src=cell.get("source","")
        if isinstance(src,list): src="".join(src)
        if ct=="markdown": parse_md(src,st,story,toc); story.append(Spacer(1,4))
        elif ct=="code":
            if src.strip(): render_code(src,st,story,n=cn)
            outs=cell.get("outputs",[])
            if outs: render_outputs(outs,cn,st,story)
            if src.strip(): cn+=1
            story.append(Spacer(1,6))
        elif ct=="raw":
            if src.strip(): block(src.splitlines(),st,story)
    ts=[]
    if toc: toc_page(toc,st,ts)
    story[ti:ti+1]=ts
    doc=SimpleDocTemplate(output_path,pagesize=A4,leftMargin=MARGIN,rightMargin=MARGIN,
        topMargin=1.6*cm,bottomMargin=1.8*cm,title=title,author="nb2pdf_agent")
    doc.build(story,canvasmaker=lambda fn,**kw:ReportCanvas(fn,doc_title=title,**kw))
    return output_path

def main():
    ap=argparse.ArgumentParser(description="nb2pdf_agent — Jupyter Notebook → PDF")
    ap.add_argument("notebook"); ap.add_argument("-o","--output",default=None)
    args=ap.parse_args()
    print(f"📓 Loading: {args.notebook}")
    print(f"✅ PDF saved: {convert_notebook(args.notebook,args.output)}")

if __name__=="__main__": main()